### ISSUE TITLE
Issue with sodium during the oxy-node installation

### ISSUE THREAD

**Issue by P1ck4ndRoll** [Oxycoin/oxy-node#7]
/root/oxy-node/oxy_manager.bash install failing on oxy-node installation due the issue with sodium.
--unsafe-perm req to make it work (npm install).

**Comment by Stoner19** [comment]
I too have been having the same issues and have yet to find a solution, but I'm still searching. Here is the full `npm` error
```
Makefile:79: recipe for target 'nodesodium' failed
make: *** [nodesodium] Error 1
/home/stone/oxy-node/node_modules/sodium/install.js:288
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make nodesodium exited with code 2
    at ChildProcess.<anonymous> (/home/stone/oxy-node/node_modules/sodium/install.js:288:19)
    at ChildProcess.emit (events.js:159:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@1.2.3 install: `node install.js --install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sodium@1.2.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
